// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynFTIhKPZUDVA6sHUZST0YS9mR4J5984',
    appId: '1:387118286779:web:8ecec89b5cec4ff5ede69e',
    messagingSenderId: '387118286779',
    projectId: 'yalla-delivery-app-f5ce2',
    authDomain: 'yalla-delivery-app-f5ce2.firebaseapp.com',
    storageBucket: 'yalla-delivery-app-f5ce2.firebasestorage.app',
    measurementId: 'G-JE7WGG7G3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWB37XIwtnSN0-grMRllcYhBup-Wm-Nus',
    appId: '1:387118286779:android:29004a5a1cb3b0b0ede69e',
    messagingSenderId: '387118286779',
    projectId: 'yalla-delivery-app-f5ce2',
    storageBucket: 'yalla-delivery-app-f5ce2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADo6gq6q4A_XeYbmzyc8BChB1ftoAOW50',
    appId: '1:387118286779:ios:8fabe1d22d004137ede69e',
    messagingSenderId: '387118286779',
    projectId: 'yalla-delivery-app-f5ce2',
    storageBucket: 'yalla-delivery-app-f5ce2.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADo6gq6q4A_XeYbmzyc8BChB1ftoAOW50',
    appId: '1:387118286779:ios:8fabe1d22d004137ede69e',
    messagingSenderId: '387118286779',
    projectId: 'yalla-delivery-app-f5ce2',
    storageBucket: 'yalla-delivery-app-f5ce2.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAynFTIhKPZUDVA6sHUZST0YS9mR4J5984',
    appId: '1:387118286779:web:df503cfa3dc226f8ede69e',
    messagingSenderId: '387118286779',
    projectId: 'yalla-delivery-app-f5ce2',
    authDomain: 'yalla-delivery-app-f5ce2.firebaseapp.com',
    storageBucket: 'yalla-delivery-app-f5ce2.firebasestorage.app',
    measurementId: 'G-V4ZFYQQGMC',
  );
}